name: Create Tag
on:
  push:
    branches:
      - main
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout actions
          uses: actions/checkout@v1

        - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7

        - name: Run Python
          run: |
            cd ${{ github.workspace }}/tools
            python new_tag.py
          